language: php
sudo: required
dist: xenial
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3snapshot

addons:
  apt:
    packages:
      # required for php7.3
      - libzip4

script:
  - ./bin/phpunit --configuration tests/phpunit.xml
  - ./bin/sabre-cs-fixer fix . --dry-run --diff

before_script:
  - composer install

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  allow_failures:
    - php: 5.5
