language: php
sudo: required
dist: xenial
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3snapshot

addons:
  apt:
    packages:
      # required for php7.3
      - libzip4

before_script:
- composer install

script:
  - ./bin/phpunit --configuration tests/phpunit.xml --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
    - tools

matrix:
  allow_failures:
    - php: 5.5
