language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm-nightly

script:
  - phpunit --configuration tests/phpunit.xml
  - ./bin/phpcs -p --standard=tests/phpcs/ruleset.xml lib/


before_script: composer install
